// <auto-generated />
using System;
using KUSYS_Demo.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KUSYS_Demo.Migrations
{
    [DbContext(typeof(KUSYSDbContext))]
    [Migration("20220612192502_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KUSYS_Demo.Domain.Course", b =>
                {
                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = "CSI101",
                            CourseName = "Introduction to Computer Science"
                        },
                        new
                        {
                            CourseId = "CSI102",
                            CourseName = "Algorithms"
                        },
                        new
                        {
                            CourseId = "MAT101",
                            CourseName = "Calculus"
                        },
                        new
                        {
                            CourseId = "PHY101",
                            CourseName = "Physics"
                        });
                });

            modelBuilder.Entity("KUSYS_Demo.Domain.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("CourseId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            BirthDate = new DateTime(2022, 6, 12, 22, 25, 2, 24, DateTimeKind.Local).AddTicks(6852),
                            CourseId = "CSI101",
                            FirstName = "Ramazan",
                            LastName = "Bayazit"
                        },
                        new
                        {
                            StudentId = 2,
                            BirthDate = new DateTime(2022, 6, 12, 22, 25, 2, 24, DateTimeKind.Local).AddTicks(6861),
                            CourseId = "CSI102",
                            FirstName = "Rıdvan",
                            LastName = "Abay"
                        },
                        new
                        {
                            StudentId = 3,
                            BirthDate = new DateTime(2022, 6, 12, 22, 25, 2, 24, DateTimeKind.Local).AddTicks(6863),
                            CourseId = "MAT101",
                            FirstName = "Mert",
                            LastName = "Artan"
                        },
                        new
                        {
                            StudentId = 4,
                            BirthDate = new DateTime(2022, 6, 12, 22, 25, 2, 24, DateTimeKind.Local).AddTicks(6864),
                            CourseId = "PHY101",
                            FirstName = "Recep",
                            LastName = "Çil"
                        });
                });

            modelBuilder.Entity("KUSYS_Demo.Domain.Student", b =>
                {
                    b.HasOne("KUSYS_Demo.Domain.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("KUSYS_Demo.Domain.Course", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
